---
name: "Build and test"
on:  # yamllint disable-line rule:truthy
  - "push"

jobs:
  nix-ci:
    uses: "christianharke/flake-commons/.github/workflows/nix-ci.yml@main"
    with:
      branch: "${{ github.ref_name }}"
      nix-command: "flake check --impure"
      system: "x86_64-linux"
    secrets:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
